"""category_rules table

Revision ID: 43814789b866
Revises: d44f27ef592c
Create Date: 2019-11-14 21:40:43.000384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43814789b866'
down_revision = 'd44f27ef592c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category_rule', sa.Column('exact_rule', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category_rule', 'exact_rule')
    # ### end Alembic commands ###
