"""rules table

Revision ID: b14a00326af8
Revises: 5b65fca811f0
Create Date: 2019-12-18 21:37:18.631301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b14a00326af8'
down_revision = '5b65fca811f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category_rule', sa.Column('max_amount', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category_rule', 'max_amount')
    # ### end Alembic commands ###
