"""category_rules table

Revision ID: d44f27ef592c
Revises: 1ce0e127b85f
Create Date: 2019-11-14 21:15:39.812848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd44f27ef592c'
down_revision = '1ce0e127b85f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('string_match', sa.String(length=100), nullable=True),
    sa.Column('date_match', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_rule_category'), 'category_rule', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_category_rule_category'), table_name='category_rule')
    op.drop_table('category_rule')
    # ### end Alembic commands ###
